# Generated by Django 4.2.1 on 2023-06-04 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_alter_buddy_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
